import React from 'react';
import { theme } from './theme';

/**
 * Global Shared Directory & Exploration Page Styles
 * Single source of truth for all catalogs: Mods, Gear, Arcanes, Relics, Resources,
 * Missions, Mechanics, Vendors, Targets, and Live World State.
 */
export const directoryStyles: Record<string, React.CSSProperties> = {
  // Page Shell & Header
  container: {
    maxWidth: 1200,
    margin: '0 auto',
    padding: '24px 16px 64px 16px',
    color: theme.colors.textPrimary,
  },
  header: {
    marginBottom: 20,
  },
  headerBadge: {
    display: 'inline-block',
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    padding: '3px 8px',
    borderRadius: theme.radii.sm,
    backgroundColor: theme.colors.accentBg,
    color: theme.colors.accent,
    border: `1px solid ${theme.colors.accentBorder}`,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: 800,
    color: theme.colors.textHighlight,
    margin: '0 0 8px 0',
  },
  subtitle: {
    fontSize: 14,
    color: theme.colors.textSecondary,
    lineHeight: 1.5,
    margin: 0,
    maxWidth: 820,
  },

  // Search & Filter Controls Toolbar
  searchControlsRow: {
    display: 'flex',
    gap: 10,
    flexWrap: 'wrap',
    alignItems: 'center',
    marginBottom: 16,
  },
  searchBarWrapper: {
    flex: '1 1 300px',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
  },
  searchInput: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px 14px',
    background: theme.colors.bgInput,
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.md,
    color: theme.colors.textHighlight,
    fontSize: 14,
    outline: 'none',
    minHeight: 40,
  },
  clearSearchBtn: {
    position: 'absolute',
    right: 10,
    padding: '4px 10px',
    backgroundColor: 'transparent',
    border: 'none',
    color: theme.colors.textMuted,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
  },
  filterToggleBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '10px 14px',
    borderRadius: theme.radii.md,
    border: `1px solid ${theme.colors.borderDefault}`,
    backgroundColor: theme.colors.bgInput,
    color: theme.colors.textSecondary,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 40,
    transition: 'all 0.15s ease',
  },
  filterCountBadge: {
    backgroundColor: theme.colors.accent,
    color: theme.colors.bgCard,
    borderRadius: theme.radii.full,
    fontSize: 10,
    fontWeight: 800,
    padding: '1px 6px',
    minWidth: 16,
    textAlign: 'center',
  },
  resetFiltersQuickBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    padding: '6px 12px',
    borderRadius: theme.radii.sm,
    border: `1px solid ${theme.colors.borderDefault}`,
    backgroundColor: 'transparent',
    color: theme.colors.textMuted,
    fontSize: 12,
    cursor: 'pointer',
    minHeight: 34,
  },

  // Desktop Direct Filter Bar
  desktopFilterBar: {
    display: 'flex',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 12,
    flex: 1,
  },
  desktopFilterGroup: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  desktopFilterLabel: {
    fontSize: 12,
    fontWeight: 700,
    color: theme.colors.textMuted,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },

  // Category Pills Strip
  categoryPillsStrip: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 16,
  },
  categoryPill: {
    padding: '6px 14px',
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.sm,
    color: theme.colors.textSecondary,
    fontSize: 12.5,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  categoryPillActive: {
    backgroundColor: theme.colors.accentBg,
    borderColor: theme.colors.accentBorder,
    color: theme.colors.accent,
    fontWeight: 700,
  },

  // Filter Drawer
  filterDrawerCard: {
    backgroundColor: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.lg,
    padding: '16px 18px',
    marginBottom: 20,
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
  },
  filterDrawerHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: 12,
    borderBottom: `1px solid ${theme.colors.borderSubtle}`,
  },
  filterDrawerTitle: {
    fontSize: 14,
    fontWeight: 700,
    color: theme.colors.textHighlight,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  closeDrawerBtn: {
    backgroundColor: 'transparent',
    border: 'none',
    color: theme.colors.textMuted,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    padding: '4px 8px',
  },
  filterGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  filterLabel: {
    fontSize: 12,
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.05em',
    color: theme.colors.textMuted,
  },
  filterPills: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 6,
  },
  filterPill: {
    padding: '6px 12px',
    backgroundColor: theme.colors.bgCardElevated,
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.sm,
    color: theme.colors.textSecondary,
    fontSize: 12,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'all 0.15s ease',
  },
  filterPillActive: {
    backgroundColor: theme.colors.accentBg,
    borderColor: theme.colors.accentBorder,
    color: theme.colors.accent,
    fontWeight: 700,
  },
  filterDrawerFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 14,
    borderTop: `1px solid ${theme.colors.borderSubtle}`,
    flexWrap: 'wrap',
    gap: 10,
  },
  resetFiltersBtn: {
    backgroundColor: 'transparent',
    border: `1px solid ${theme.colors.borderDefault}`,
    color: theme.colors.accent,
    padding: '6px 12px',
    borderRadius: theme.radii.sm,
    fontSize: 12,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    minHeight: 34,
  },
  applyFiltersBtn: {
    backgroundColor: theme.colors.accentBg,
    border: `1px solid ${theme.colors.accentBorder}`,
    color: theme.colors.textHighlight,
    padding: '6px 14px',
    borderRadius: theme.radii.sm,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 34,
  },

  // Results Info Bar
  resultsInfoBar: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
    padding: '8px 12px',
    backgroundColor: theme.colors.bgCardElevated,
    borderRadius: theme.radii.md,
    border: `1px solid ${theme.colors.borderDefault}`,
    flexWrap: 'wrap',
    gap: 8,
  },
  resultsCount: {
    fontSize: 13,
    color: theme.colors.textSecondary,
  },

  // Card Grids
  cardGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: 16,
  },
  cardGrid3Col: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(320px, 1fr))',
    gap: 16,
  },

  // Entity Cards
  card: {
    background: theme.colors.bgCard,
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.lg,
    padding: 16,
    display: 'flex',
    flexDirection: 'column',
    transition: 'border-color 0.15s ease',
  },
  cardHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottom: `1px solid ${theme.colors.borderSubtle}`,
  },
  thumbArea: {
    width: 52,
    height: 52,
    borderRadius: theme.radii.md,
    backgroundColor: theme.colors.bgCardElevated,
    border: `1px solid ${theme.colors.borderSubtle}`,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
    overflow: 'hidden',
    padding: 2,
    boxSizing: 'border-box',
  },
  thumbImg: {
    width: '100%',
    height: '100%',
    maxWidth: '100%',
    maxHeight: '100%',
    objectFit: 'contain',
    display: 'block',
  },
  thumbFallback: {
    fontSize: 22,
    color: theme.colors.textSecondary,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerTitles: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  badgeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    flexWrap: 'wrap',
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: 700,
    color: theme.colors.textHighlight,
    margin: 0,
  },
  cardTitleLink: {
    fontSize: 16,
    fontWeight: 700,
    color: theme.colors.textHighlight,
    textDecoration: 'none',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  targetBtn: {
    padding: '6px 12px',
    border: `1px solid ${theme.colors.borderDefault}`,
    borderRadius: theme.radii.sm,
    fontSize: 12,
    fontWeight: 600,
    cursor: 'pointer',
    flexShrink: 0,
    transition: 'all 0.15s ease',
    backgroundColor: theme.colors.bgInput,
    color: theme.colors.textSecondary,
  },
  targetBtnActive: {
    backgroundColor: theme.colors.gold,
    color: theme.colors.textInverse,
    borderColor: theme.colors.goldBorder,
  },
  cardBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    flex: 1,
  },
  cardDescription: {
    fontSize: 12.5,
    color: theme.colors.textSecondary,
    lineHeight: 1.45,
    margin: '0 0 10px 0',
  },

  // Drop Locations & Notes
  dropsSection: {
    marginTop: 10,
    paddingTop: 10,
    borderTop: `1px solid ${theme.colors.borderSubtle}`,
  },
  dropsHeaderRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  dropsTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: theme.colors.green,
    textTransform: 'uppercase',
    letterSpacing: '0.04em',
  },
  expandDropsBtn: {
    background: 'none',
    border: 'none',
    color: theme.colors.accent,
    fontSize: 11,
    fontWeight: 600,
    cursor: 'pointer',
    padding: 0,
  },
  dropsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  dropItem: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontSize: 11.5,
    padding: '3px 6px',
    backgroundColor: theme.colors.bgCardElevated,
    borderRadius: theme.radii.sm,
  },
  dropLocation: {
    color: theme.colors.textSecondary,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    marginRight: 8,
  },
  dropRateVal: {
    color: theme.colors.green,
    fontWeight: 700,
    flexShrink: 0,
  },

  // Pagination & Empty State
  loadMoreContainer: {
    textAlign: 'center',
    marginTop: 20,
  },
  loadMoreBtn: {
    padding: '10px 22px',
    backgroundColor: theme.colors.accentBg,
    border: `1px solid ${theme.colors.accentBorder}`,
    borderRadius: theme.radii.sm,
    color: theme.colors.accent,
    fontSize: 13,
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 40,
  },
  emptyNoticeBox: {
    padding: '30px 20px',
    textAlign: 'center',
    backgroundColor: theme.colors.bgCardElevated,
    borderRadius: theme.radii.md,
    border: `1px solid ${theme.colors.borderSubtle}`,
  },
  emptyNoticeText: {
    fontSize: 14,
    color: theme.colors.textMuted,
    margin: '0 0 12px 0',
  },
};

