import React from 'react';

export function getRarityBadgeStyle(rarity?: string): React.CSSProperties {
  const r = (rarity || '').toLowerCase();
  if (r.includes('legendary')) {
    return {
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: 4,
      fontSize: 11,
      fontWeight: 600,
      backgroundColor: '#f5f5f518',
      border: '1px solid #ffffff44',
      color: '#ffffff',
    };
  }
  if (r.includes('rare')) {
    return {
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: 4,
      fontSize: 11,
      fontWeight: 600,
      backgroundColor: '#ffd70018',
      border: '1px solid #ffd70044',
      color: '#ffd700',
    };
  }
  if (r.includes('uncommon')) {
    return {
      display: 'inline-block',
      padding: '2px 8px',
      borderRadius: 4,
      fontSize: 11,
      fontWeight: 600,
      backgroundColor: '#90caf918',
      border: '1px solid #90caf944',
      color: '#90caf9',
    };
  }
  return {
    display: 'inline-block',
    padding: '2px 8px',
    borderRadius: 4,
    fontSize: 11,
    fontWeight: 600,
    backgroundColor: '#d49b6a18',
    border: '1px solid #d49b6a44',
    color: '#eed8c4',
  };
}

export const detailStyles: Record<string, React.CSSProperties> = {
  container: {
    padding: '16px 18px 60px 18px',
    maxWidth: 1040,
    margin: '0 auto',
  },
  breadcrumbNav: {
    marginBottom: 16,
  },
  backLink: {
    color: '#8a8aa8',
    textDecoration: 'none',
    fontSize: 13,
  },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 16,
    paddingBottom: 20,
    borderBottom: '1px solid #1c1c28',
    marginBottom: 24,
  },
  headerLeft: {
    display: 'flex',
    alignItems: 'center',
    gap: 16,
    flexWrap: 'wrap',
  },
  headerInfo: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  title: {
    fontSize: 26,
    fontWeight: 700,
    color: '#eaeaf0',
    margin: 0,
  },
  categoryBadge: {
    alignSelf: 'flex-start',
    fontSize: 11,
    padding: '3px 8px',
    background: '#1c1c2c',
    color: '#9090b8',
    borderRadius: 4,
  },
  wikiLink: {
    fontSize: 12,
    color: '#6e8ec4',
    textDecoration: 'none',
  },
  targetWidget: {
    display: 'flex',
    alignItems: 'center',
  },
  targetControls: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  targetButton: {
    padding: '8px 14px',
    border: '1px solid',
    borderRadius: 4,
    fontSize: 13,
    cursor: 'pointer',
    fontWeight: 500,
  },
  qtyBox: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  qtyLabel: {
    fontSize: 12,
    color: '#8a8aa0',
  },
  qtyInput: {
    width: 60,
    padding: '6px 8px',
    background: '#14141c',
    border: '1px solid #282838',
    borderRadius: 4,
    color: '#e0e0e8',
    fontSize: 13,
    textAlign: 'center',
  },
  statusNotice: {
    color: '#8a8aa0',
    fontSize: 14,
  },
  errorNotice: {
    color: '#c48a8a',
    fontSize: 14,
    marginBottom: 12,
  },
  contentGrid: {
    display: 'grid',
    gridTemplateColumns: '1fr 300px',
    gap: 24,
  },
  mainColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  sideColumn: {
    display: 'flex',
    flexDirection: 'column',
    gap: 20,
  },
  sectionCard: {
    background: '#12121a',
    border: '1px solid #1e1e2c',
    borderRadius: 6,
    padding: 20,
  },
  componentParentCard: {
    background: '#141420',
    border: '1px solid #2a2a3e',
    borderLeft: '4px solid #ffd700',
    borderRadius: 6,
    padding: 16,
  },
  componentParentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 12,
  },
  componentBadge: {
    fontSize: 11,
    fontWeight: 700,
    padding: '2px 8px',
    borderRadius: 4,
    background: '#2d2218',
    color: '#ffd700',
    border: '1px solid #5c4820',
  },
  parentItemLink: {
    fontSize: 14,
    fontWeight: 700,
    color: '#ffd700',
    textDecoration: 'none',
  },
  baseVariantLink: {
    fontSize: 12,
    fontWeight: 600,
    color: '#77aaff',
    textDecoration: 'none',
    padding: '4px 10px',
    background: '#162030',
    border: '1px solid #204060',
    borderRadius: 4,
  },
  siblingStrip: {
    marginTop: 14,
    paddingTop: 12,
    borderTop: '1px solid #242436',
  },
  siblingStripLabel: {
    fontSize: 12,
    fontWeight: 600,
    color: '#9098b8',
    display: 'block',
    marginBottom: 8,
  },
  siblingList: {
    display: 'flex',
    gap: 8,
    flexWrap: 'wrap',
  },
  siblingChip: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '5px 10px',
    background: '#161622',
    border: '1px solid #262638',
    borderRadius: 4,
    color: '#d0d4e8',
    fontSize: 12,
    textDecoration: 'none',
    fontWeight: 500,
  },
  siblingChipActive: {
    background: '#2a2216',
    borderColor: '#785420',
    color: '#ffd700',
    fontWeight: 700,
  },
  viewingIndicator: {
    fontSize: 11,
    color: '#e0a860',
    fontWeight: 700,
  },
  partPageLink: {
    fontSize: 11.5,
    fontWeight: 600,
    color: '#8ec4f4',
    textDecoration: 'none',
    padding: '4px 8px',
    background: '#1c2438',
    borderRadius: 4,
    border: '1px solid #2a3654',
    transition: 'background 0.2s',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: '#dcdce8',
    marginBottom: 14,
  },
  sectionSubTitle: {
    fontSize: 14,
    fontWeight: 600,
    color: '#c4c4d4',
    marginBottom: 8,
  },
  itemImage: {
    maxHeight: 140,
    maxWidth: 200,
    objectFit: 'contain',
    borderRadius: 4,
    marginBottom: 12,
    background: '#181824',
    padding: 8,
  },
  extractText: {
    fontSize: 13,
    lineHeight: 1.6,
    color: '#a0a0b8',
    margin: 0,
  },
  mechanicCallout: {
    marginTop: 14,
    padding: '10px 14px',
    background: '#1e1c22',
    borderLeft: '3px solid #b89a64',
    borderRadius: 3,
    fontSize: 12,
    color: '#d0c4aa',
    lineHeight: 1.4,
  },
  nodeList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  nodeCard: {
    background: '#161622',
    border: '1px solid #202030',
    borderRadius: 4,
    padding: 12,
  },
  nodeCardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 6,
  },
  nodeName: {
    fontSize: 14,
    fontWeight: 600,
    color: '#e0e0ec',
  },
  nodePlanet: {
    fontSize: 13,
    color: '#8a8aa0',
  },
  missionTypeBadge: {
    marginLeft: 8,
    fontSize: 11,
    padding: '2px 6px',
    background: '#222232',
    borderRadius: 3,
    color: '#9090b0',
  },
  efficiencyBadge: {
    fontSize: 11,
    fontWeight: 600,
  },
  dropRateBadge: {
    fontSize: 11,
    color: '#8ec48e',
    fontWeight: 500,
  },
  strategyText: {
    fontSize: 12,
    color: '#8a8aa4',
    margin: 0,
    lineHeight: 1.4,
  },
  framesTipBox: {
    marginTop: 16,
    padding: '10px 12px',
    background: '#161622',
    borderRadius: 4,
    fontSize: 12,
  },
  framesTipTitle: {
    color: '#c0c0d4',
    marginRight: 6,
  },
  framesList: {
    color: '#8e9ec4',
  },
  notesHelp: {
    fontSize: 12,
    color: '#7a7a90',
    marginBottom: 10,
    lineHeight: 1.3,
  },
  notesTextarea: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '10px',
    background: '#161622',
    border: '1px solid #262638',
    borderRadius: 4,
    color: '#d0d0dc',
    fontSize: 12,
    lineHeight: 1.4,
    resize: 'vertical',
    outline: 'none',
  },
  notesActions: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginTop: 8,
  },
  saveNoteBtn: {
    padding: '5px 12px',
    background: '#202030',
    border: '1px solid #2e2e44',
    borderRadius: 3,
    color: '#b0b0c8',
    fontSize: 12,
    cursor: 'pointer',
  },
  planetList: {
    listStyle: 'none',
    padding: 0,
    margin: 0,
  },
  planetItem: {
    fontSize: 12,
    color: '#8a8aa4',
    padding: '3px 0',
  },
  lootSummaryBox: {
    background: '#161622',
    borderRadius: 4,
    padding: 12,
    marginBottom: 14,
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  lootInfoRow: {
    display: 'flex',
    alignItems: 'center',
    fontSize: 13,
    gap: 8,
  },
  lootInfoLabel: {
    color: '#84849a',
    minWidth: 140,
  },
  lootInfoValue: {
    color: '#e0e0ec',
    fontWeight: 600,
  },
  lootGeneralText: {
    fontSize: 12,
    color: '#9a9ab0',
    margin: '6px 0 0 0',
    lineHeight: 1.4,
  },
  componentsTable: {
    display: 'flex',
    flexDirection: 'column',
    gap: 6,
  },
  componentsHeader: {
    fontSize: 12,
    fontWeight: 600,
    color: '#b0b0c4',
    marginBottom: 4,
  },
  componentRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    background: '#161622',
    border: '1px solid #202030',
    borderRadius: 4,
    padding: '8px 12px',
    fontSize: 12,
  },
  componentName: {
    fontWeight: 500,
    color: '#e4e4ee',
  },
  componentRight: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
  },
  componentSource: {
    color: '#8a8aa0',
  },
  componentChance: {
    color: '#8ec48e',
    fontWeight: 600,
  },
  blockTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#c0c0d8',
    display: 'block',
    marginBottom: 6,
  },
  solutionList: {
    paddingLeft: 20,
    margin: 0,
    fontSize: 12,
    color: '#9090a8',
    lineHeight: 1.6,
  },
  acquisitionCard: {
    background: '#141420',
    border: '1px solid #28283e',
    borderLeft: '4px solid #8eb4e4',
    borderRadius: 6,
    padding: 16,
    marginBottom: 20,
  },
  acquisitionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  acquisitionBadge: {
    fontSize: 11,
    padding: '2px 8px',
    background: '#222b3a',
    color: '#8ec4f4',
    borderRadius: 3,
    fontWeight: 600,
    textTransform: 'uppercase',
  },
  vendorStoreTag: {
    fontSize: 12,
    color: '#8a8aa4',
  },
  acquisitionSentence: {
    fontSize: 14,
    color: '#e4e4f0',
    lineHeight: 1.5,
    margin: '0 0 6px 0',
  },
  standingHighlight: {
    color: '#90d490',
    fontWeight: 600,
  },
  vendorNotes: {
    fontSize: 12,
    color: '#8e8ea4',
    margin: 0,
    lineHeight: 1.4,
  },
  vendorMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 16,
    fontSize: 12,
    color: '#9a9ab0',
    marginTop: 6,
  },
  rankTableWrapper: {
    overflowX: 'auto',
  },
  rankTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 12,
    textAlign: 'left',
  },
  rankTh: {
    padding: '8px 10px',
    borderBottom: '1px solid #242436',
    color: '#8c8ca4',
    fontWeight: 600,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  rankTd: {
    padding: '8px 10px',
    borderBottom: '1px solid #1a1a26',
    color: '#dcdce8',
  },
  rankBadge: {
    display: 'inline-block',
    minWidth: 22,
    textAlign: 'center',
    padding: '2px 6px',
    background: '#1a1a28',
    borderRadius: 3,
    fontWeight: 600,
    color: '#c0c0d8',
  },
  costBadge: {
    display: 'inline-block',
    padding: '2px 6px',
    background: '#182418',
    color: '#8ec48e',
    borderRadius: 3,
    fontWeight: 600,
  },
  statTd: {
    padding: '8px 10px',
    borderBottom: '1px solid #1a1a26',
    color: '#8ec4c4',
    fontWeight: 500,
  },
  effectTd: {
    padding: '8px 10px',
    borderBottom: '1px solid #1a1a26',
    color: '#a0a0b8',
    lineHeight: 1.4,
  },
  maxRankRow: {
    background: '#161626',
  },
  infoBox: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  infoRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '4px 0',
    borderBottom: '1px solid #181824',
    fontSize: 12,
  },
  infoLabel: {
    color: '#828298',
  },
  infoVal: {
    color: '#dcdce6',
    fontWeight: 500,
    textAlign: 'right',
  },
  dropTablesLink: {
    color: '#6e8ec4',
    textDecoration: 'none',
    fontSize: 12,
  },
  craftCostText: {
    fontSize: 12,
    color: '#8a8aa4',
  },
  cookTimeBadge: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    background: '#1c1c2c',
    padding: '4px 10px',
    borderRadius: 4,
    border: '1px solid #2a2a3e',
  },
  cookTimeLabel: {
    fontSize: 11,
    color: '#8a8aa0',
  },
  cookTimeValue: {
    fontSize: 12,
    fontWeight: 700,
    color: '#90d490',
  },
  ingredientsBlock: {
    marginTop: 12,
    marginBottom: 16,
  },
  ingredientsTitle: {
    fontSize: 12,
    fontWeight: 600,
    color: '#b0b0c4',
    display: 'block',
    marginBottom: 8,
  },
  ingredientsGrid: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  componentRecipesSection: {
    marginTop: 14,
  },
  componentsHeading: {
    fontSize: 12,
    fontWeight: 600,
    color: '#b0b0c4',
    display: 'block',
    marginBottom: 8,
  },
  componentRecipesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  },
  compRecipeBox: {
    background: '#161622',
    border: '1px solid #202030',
    borderRadius: 4,
    padding: 10,
  },
  compRecipeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  compRecipeName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e0e0ec',
  },
  compRecipeMeta: {
    fontSize: 11,
    color: '#8a8aa0',
  },
  statsSummaryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))',
    gap: 8,
    marginTop: 10,
  },
  statsSummaryCard: {
    background: '#161622',
    border: '1px solid #202032',
    borderRadius: 4,
    padding: '8px 10px',
  },
  statsSummaryLabel: {
    fontSize: 10,
    color: '#8888a2',
    textTransform: 'uppercase',
    display: 'block',
    marginBottom: 2,
  },
  statsSummaryVal: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e0e0ee',
  },
  damageModesList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 6,
  },
  damageModeBox: {
    background: '#161622',
    border: '1px solid #202032',
    borderRadius: 4,
    padding: 10,
  },
  damageModeHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  damageModeTitle: {
    fontSize: 13,
    fontWeight: 600,
    color: '#d0d0e4',
  },
  damageModeTotal: {
    fontSize: 12,
    fontWeight: 700,
    color: '#90d490',
  },
  damageTypesRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  damageTypeChip: {
    background: '#1b1b2a',
    border: '1px solid #28283c',
    borderRadius: 3,
    padding: '3px 8px',
    display: 'flex',
    gap: 6,
    fontSize: 11,
  },
  damageTypeLabel: {
    color: '#9090a8',
  },
  damageTypeValue: {
    color: '#e0e0ee',
    fontWeight: 600,
  },
  augmentsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 6,
  },
  augmentCard: {
    background: '#161622',
    border: '1px solid #202032',
    borderRadius: 4,
    padding: 10,
  },
  augmentHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  augmentLink: {
    fontSize: 13,
    fontWeight: 600,
    color: '#8ec4f4',
    textDecoration: 'none',
  },
  augmentSource: {
    fontSize: 11,
    color: '#8888a0',
  },
  augmentEffect: {
    fontSize: 12,
    color: '#c0c0d4',
    margin: 0,
    lineHeight: 1.4,
  },
  variantsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    marginTop: 6,
  },
  variantCard: {
    background: '#161622',
    border: '1px solid #202032',
    borderRadius: 4,
    padding: 10,
  },
  variantName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#e0e0ee',
    display: 'block',
    marginBottom: 2,
  },
  variantAcq: {
    fontSize: 12,
    color: '#9090a8',
    margin: '0 0 4px 0',
    lineHeight: 1.4,
  },
  variantBonus: {
    fontSize: 11,
    color: '#90d490',
    margin: 0,
  },
  abilitiesList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: 12,
    marginTop: 10,
  },
  abilityCard: {
    background: '#161622',
    border: '1px solid #202032',
    borderRadius: 4,
    padding: 12,
  },
  abilityHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    marginBottom: 6,
  },
  abilityIndexBadge: {
    fontSize: 10,
    fontWeight: 700,
    textTransform: 'uppercase',
    background: '#1f2538',
    color: '#8ec4f4',
    padding: '2px 6px',
    borderRadius: 3,
    border: '1px solid #2c3650',
  },
  abilityName: {
    fontSize: 14,
    fontWeight: 700,
    color: '#e0e0ee',
  },
  abilityDescription: {
    fontSize: 12,
    color: '#a0a0b8',
    lineHeight: 1.5,
    margin: 0,
  },
  enemyDropsTableWrapper: {
    overflowX: 'auto',
    marginTop: 8,
  },
  enemyDropsTable: {
    width: '100%',
    borderCollapse: 'collapse',
    fontSize: 12.5,
    textAlign: 'left',
  },
  enemyDropsTh: {
    padding: '8px 10px',
    borderBottom: '1px solid #242436',
    color: '#8c8ca4',
    fontWeight: 600,
    fontSize: 11,
    textTransform: 'uppercase',
  },
  enemyDropRow: {
    borderBottom: '1px solid #1a1a26',
  },
  enemyDropNameCell: {
    padding: '10px 10px',
    color: '#e4e4ee',
    fontWeight: 500,
  },
  enemyNameText: {
    color: '#e0e4f4',
    fontWeight: 500,
  },
  enemyDropStatCell: {
    padding: '10px 10px',
    color: '#c0c8e0',
  },
  enemyDropRateCell: {
    padding: '10px 10px',
  },
  expectedRateBadge: {
    display: 'inline-block',
    padding: '2px 7px',
    borderRadius: 3,
    fontSize: 11.5,
    fontWeight: 600,
    backgroundColor: '#00e67618',
    border: '1px solid #00e67644',
    color: '#00e676',
  },
  enemyDropRarityCell: {
    padding: '10px 10px',
  },
  incarnonCard: {
    background: '#161224',
    border: '1px solid #3d2b56',
    borderLeft: '4px solid #b877f0',
    borderRadius: 6,
    padding: 20,
  },
  incarnonHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
    paddingBottom: 12,
    borderBottom: '1px solid #281e3a',
  },
  incarnonBadge: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: '0.5px',
    padding: '4px 10px',
    background: '#321c4e',
    color: '#e4b8ff',
    borderRadius: 4,
    border: '1px solid #58338a',
  },
  incarnonCircuitBadge: {
    fontSize: 12,
    fontWeight: 600,
    padding: '4px 10px',
    background: '#1b2238',
    color: '#8ec5fc',
    borderRadius: 4,
    border: '1px solid #2c3e6b',
  },
  incarnonRequirementsBox: {
    marginBottom: 18,
    padding: '14px 16px',
    background: '#100c1c',
    borderRadius: 6,
    border: '1px solid #2d1e44',
  },
  incarnonReqHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'baseline',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  incarnonReqTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#eed8ff',
  },
  incarnonReqSub: {
    fontSize: 11.5,
    color: '#a090b8',
  },
  incarnonMetaRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 16,
    fontSize: 13,
    color: '#c4b8dc',
    marginBottom: 14,
    padding: '8px 12px',
    background: '#1c162e',
    borderRadius: 4,
  },
  incarnonOverviewBox: {
    marginBottom: 18,
    padding: '12px 14px',
    background: '#120e20',
    borderRadius: 4,
    borderLeft: '3px solid #7c4dff',
  },
  incarnonOverviewTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#d4b8ff',
    marginBottom: 6,
  },
  incarnonOverviewText: {
    margin: '0 0 8px 0',
    fontSize: 12.5,
    lineHeight: 1.55,
    color: '#d0c4e8',
  },
  incarnonEvolutionsHeader: {
    fontSize: 15,
    fontWeight: 700,
    color: '#eed8ff',
    margin: '18px 0 12px 0',
  },
  incarnonTierCard: {
    background: '#110d1f',
    border: '1px solid #2a1c3d',
    borderRadius: 6,
    padding: 14,
    marginBottom: 12,
  },
  incarnonTierTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
    paddingBottom: 8,
    borderBottom: '1px solid #201433',
  },
  incarnonTierName: {
    fontSize: 13.5,
    fontWeight: 700,
    color: '#f0e0ff',
  },
  incarnonChallengeBadge: {
    fontSize: 11.5,
    padding: '3px 8px',
    background: '#241a38',
    color: '#c4b0e8',
    borderRadius: 3,
    border: '1px solid #3c2a5c',
  },
  incarnonPerksGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: 10,
  },
  incarnonPerkBox: {
    background: '#171228',
    border: '1px solid #2e1e48',
    borderRadius: 4,
    padding: 10,
  },
  incarnonPerkName: {
    fontSize: 13,
    fontWeight: 600,
    color: '#ffd580',
    marginBottom: 4,
  },
  incarnonPerkDesc: {
    fontSize: 12,
    lineHeight: 1.5,
    color: '#e2d8f0',
    margin: 0,
    whiteSpace: 'pre-line',
  },
  incarnonPerkNotes: {
    fontSize: 11,
    lineHeight: 1.4,
    color: '#a898c0',
    marginTop: 6,
    paddingTop: 6,
    borderTop: '1px dashed #2c1e44',
  },
  variantComparisonCard: {
    background: '#131520',
    border: '1px solid #23273c',
    borderLeft: '4px solid #7c4dff',
    borderRadius: 6,
    padding: 20,
    marginBottom: 20,
  },
  variantHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    flexWrap: 'wrap',
    gap: 12,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottom: '1px solid #1f2334',
  },
  variantBadge: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: '0.6px',
    padding: '3px 8px',
    background: '#281c4a',
    color: '#d6b8ff',
    borderRadius: 4,
    border: '1px solid #4a2d80',
  },
  variantFamilyText: {
    fontSize: 13,
    color: '#a8acc8',
  },
  variantSubtitle: {
    fontSize: 13,
    color: '#8e94b2',
    margin: 0,
    lineHeight: 1.4,
  },
  openVariantBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 14px',
    background: '#1e2436',
    border: '1px solid #3d4a6a',
    borderRadius: 4,
    color: '#70b4ff',
    fontSize: 12.5,
    fontWeight: 600,
    textDecoration: 'none',
    minHeight: 36,
  },
  variantTabsRow: {
    marginBottom: 16,
  },
  variantTabsLabel: {
    display: 'block',
    fontSize: 12,
    fontWeight: 600,
    color: '#8e94b2',
    marginBottom: 8,
  },
  variantTabsList: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 8,
  },
  variantTabBtn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '7px 12px',
    background: '#181a26',
    border: '1px solid #282c40',
    borderRadius: 4,
    color: '#c0c4dc',
    fontSize: 12.5,
    cursor: 'pointer',
    minHeight: 34,
  },
  variantTabBtnSelected: {
    background: '#252b42',
    borderColor: '#546b9e',
    color: '#f0f4ff',
    boxShadow: '0 0 0 1px #546b9e',
  },
  variantTabBtnCurrent: {
    background: '#161e18',
    borderColor: '#24482c',
    color: '#8ec492',
    cursor: 'default',
    opacity: 0.85,
  },
  variantTypeTag: {
    fontSize: 10,
    fontWeight: 700,
    padding: '2px 5px',
    background: '#10121a',
    borderRadius: 3,
    color: '#8e94b2',
    textTransform: 'uppercase',
  },
  variantNameText: {
    fontWeight: 600,
  },
  currentIndicator: {
    fontSize: 11,
    fontStyle: 'italic',
    color: '#78a87c',
  },
  comparisonTableWrapper: {
    overflowX: 'auto',
    borderRadius: 4,
    border: '1px solid #202436',
  },
  comparisonTable: {
    width: '100%',
    borderCollapse: 'collapse',
    textAlign: 'left',
    fontSize: 13,
  },
  compTh: {
    padding: '10px 14px',
    background: '#151724',
    color: '#8e94b2',
    fontWeight: 600,
    fontSize: 12,
    borderBottom: '1px solid #23273a',
  },
  compThCurrent: {
    padding: '10px 14px',
    background: '#161b24',
    borderBottom: '1px solid #23273a',
  },
  compThCounterpart: {
    padding: '10px 14px',
    background: '#1a1828',
    borderBottom: '1px solid #23273a',
  },
  compThDelta: {
    padding: '10px 14px',
    background: '#151724',
    color: '#8e94b2',
    fontWeight: 600,
    fontSize: 12,
    borderBottom: '1px solid #23273a',
  },
  compThSub: {
    display: 'block',
    fontSize: 10.5,
    fontWeight: 600,
    textTransform: 'uppercase',
    color: '#888ca8',
    letterSpacing: '0.4px',
  },
  compThTitle: {
    fontSize: 13,
    fontWeight: 700,
    color: '#f0f0f8',
    marginTop: 2,
  },
  compTr: {
    borderBottom: '1px solid #1c1f2e',
  },
  compTdLabel: {
    padding: '10px 14px',
    fontWeight: 600,
    color: '#d0d4e8',
    background: '#12141f',
  },
  compTdCurrent: {
    padding: '10px 14px',
    color: '#e4e6f4',
    background: '#141624',
  },
  compTdCounterpart: {
    padding: '10px 14px',
    color: '#e4e6f4',
    background: '#171626',
    fontWeight: 600,
  },
  compTdDelta: {
    padding: '10px 14px',
    background: '#12141f',
  },
  deltaBadge: {
    display: 'inline-block',
    padding: '3px 8px',
    borderRadius: 3,
    fontSize: 11.5,
    fontWeight: 600,
    border: '1px solid',
  },
  primeRelicsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
  },
  primeRelicPartGroup: {
    background: '#101218',
    border: '1px solid #1f2334',
    borderRadius: 8,
    overflow: 'hidden',
    transition: 'border-color 0.2s ease',
  },
  primeRelicPartHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 8,
    borderBottom: '1px solid #1a1e2c',
  },
  primeRelicPartTitle: {
    fontSize: 14.5,
    fontWeight: 700,
    color: '#f4f4fa',
    letterSpacing: '0.3px',
  },
  primeRelicPartCount: {
    fontSize: 12,
    color: '#8e94b2',
    fontWeight: 600,
  },
  relicBadgesGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: 12,
    padding: '16px',
    backgroundColor: '#0d0f16',
  },
  primeRelicCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    background: '#151722',
    border: '1px solid #202436',
    borderRadius: 6,
    padding: '12px 14px',
    transition: 'opacity 0.2s ease',
  },
  primeRelicCardTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eraChip: {
    display: 'inline-block',
    padding: '2px 7px',
    borderRadius: 3,
    fontSize: 11.5,
    fontWeight: 700,
    letterSpacing: '0.3px',
  },
  primeRelicChancesRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 8,
    marginTop: 2,
    borderTop: '1px solid #1f2334',
  },
  relicChanceText: {
    fontSize: 11.5,
    color: '#8e94b2',
  },
  variantToggleBtn: {
    padding: '8px 14px',
    background: '#281c4a',
    border: '1px solid #5a3899',
    borderRadius: 4,
    color: '#d6b8ff',
    fontSize: 12.5,
    fontWeight: 600,
    cursor: 'pointer',
    minHeight: 36,
  },
  primeRelicAccordionHeaderBtn: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '14px 16px',
    cursor: 'pointer',
    textAlign: 'left',
    color: 'inherit',
    border: 'none',
    outline: 'none',
    transition: 'background-color 0.15s ease',
  },
  highestDropBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 8px',
    borderRadius: 4,
    backgroundColor: '#142a1a',
    color: '#7ae08a',
    border: '1px solid #23582e',
  },
  unvaultedCountBadge: {
    fontSize: 11,
    fontWeight: 600,
    padding: '3px 8px',
    borderRadius: 4,
    backgroundColor: '#1b2234',
    color: '#90caf9',
    border: '1px solid #2e3e60',
  },
  accordionToggleWrapper: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 28,
    height: 28,
    borderRadius: '50%',
    backgroundColor: '#1c2032',
  },
  accordionToggleArrow: {
    fontSize: 12,
    color: '#8e94b2',
    transition: 'transform 0.3s cubic-bezier(0.4, 0, 0.2, 1)',
  },
  notFoundContainer: {
    padding: '28px 24px',
    background: '#12141f',
    border: '1px solid #23273c',
    borderRadius: 8,
    marginTop: 12,
  },
  notFoundHeader: {
    marginBottom: 20,
  },
  notFoundTitle: {
    fontSize: 22,
    fontWeight: 700,
    color: '#f0f0f8',
    margin: '0 0 8px 0',
  },
  notFoundSub: {
    fontSize: 14,
    color: '#9a9eb8',
    margin: 0,
    lineHeight: 1.5,
  },
  suggestionsSection: {
    marginTop: 20,
    paddingTop: 20,
    borderTop: '1px solid #1c2032',
  },
  suggestionsTitle: {
    fontSize: 15,
    fontWeight: 600,
    color: '#ffd700',
    margin: '0 0 14px 0',
  },
  suggestionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(220px, 1fr))',
    gap: 12,
  },
  suggestionCard: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '10px 14px',
    background: '#161826',
    border: '1px solid #242940',
    borderRadius: 6,
    textDecoration: 'none',
    transition: 'all 0.15s ease',
  },
  suggestionDetails: {
    display: 'flex',
    flexDirection: 'column',
    gap: 3,
    overflow: 'hidden',
  },
  suggestionName: {
    fontSize: 13.5,
    fontWeight: 600,
    color: '#e4e6f4',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  suggestionCategory: {
    display: 'flex',
    alignItems: 'center',
    gap: 6,
  },
  suggestionBadge: {
    fontSize: 10.5,
    fontWeight: 700,
    padding: '1px 5px',
    borderRadius: 3,
    background: '#22283c',
    color: '#90caf9',
  },
  suggestionSubtype: {
    fontSize: 11,
    color: '#8e94b2',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  primarySearchLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 16px',
    background: '#24324c',
    border: '1px solid #3c5482',
    borderRadius: 4,
    color: '#8ec4f4',
    fontSize: 13,
    fontWeight: 600,
    textDecoration: 'none',
  },
  secondarySearchLink: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 6,
    padding: '8px 16px',
    background: '#181b28',
    border: '1px solid #282e44',
    borderRadius: 4,
    color: '#a0a4c0',
    fontSize: 13,
    fontWeight: 600,
    textDecoration: 'none',
  },
};

